# Generated by Django 3.2 on 2021-08-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('in_store', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('isbn_number', models.CharField(max_length=13)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
